<?php

namespace olivier\BlogBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BlogController__JMSInjector
{
    public static function inject($container) {
        $instance = new \olivier\BlogBundle\Controller\BlogController();
        return $instance;
    }
}
